sudo: false

language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - nightly
  - hhvm
  - hhvm-nightly

matrix:
    allow_failures:
        - php: nightly
        - php: hhvm-nightly

before_script:
  - composer --prefer-source --dev install

script: phpunit -v -c phpunit.xml --coverage-text